export const widgets = [
    { id: 'setup', title: 'Project Setup', complete: true },
    { id: 'auth', title: 'Authentication', complete: true },
    { id: 'users', title: 'Users Management', complete: true },
    { id: 'access-control', title: 'Roles & Permissions', complete: true },
    { id: 'leads', title: 'Leads', complete: true },
    { id: 'customers', title: 'Customers', complete: true },
    { id: 'contacts', title: 'Contacts', complete: true },
    { id: 'activities', title: 'Activities', complete: true },
    { id: 'deals', title: 'Deals', complete: true },
    { id: 'support-tickets', title: 'Support Tickets', complete: true },
    { id: 'notifications', title: 'Notifications', complete: true },
    { id: 'data-transfer', title: 'Data Transfer', complete: true },
    { id: 'reports', title: 'Reports & Analytics', complete: true },
];
